import re

with open('/Users/evanvosh/Documents/app1.1/src/shared/ui/components/ExEquityCurve3D.vue', 'r') as f:
    content = f.read()

new_terms = """const terms: Record<string, { key: string, format: string, source?: string }> = {
          'Winning Trades PnL': { key: 'grossProfit', format: 'currency' },
          'Losing Trades PnL': { key: 'grossLoss', format: 'currency' },
          'Strategy Gross Profit': { key: 'grossProfit', format: 'currency' },
          'Strategy Gross Loss': { key: 'grossLoss', format: 'currency' },
          'Gross Profit': { key: 'grossProfit', format: 'currency' },
          'Gross Loss': { key: 'grossLoss', format: 'currency' },
          'Net Profit': { key: 'netProfit', format: 'currency' },
          'Winning Trades': { key: 'numWin', format: 'number' },
          'Losing Trades': { key: 'numLoss', format: 'number' },
          'Total Trades': { key: 'numTrades', format: 'number' },
          'Average Win': { key: 'avgWin', format: 'currency' },
          'Average Loss': { key: 'avgLoss', format: 'currency' },
          'AvgWin': { key: 'avgWin', format: 'currency' },
          'AvgLoss': { key: 'avgLoss', format: 'currency' },
          'Initial Deposit': { key: 'initialDeposit', format: 'currency' },
          'Payoff Ratio': { key: 'payoffRatio', format: 'number' },
          'Win%': { key: 'winRate', format: 'percent' },
          'Loss%': { key: 'lossRate', format: 'percent' },
          'Planned RR': { key: 'riskRewardRatio', format: 'number' },
          'Maximum Drawdown %': { key: 'maxDrawdownPct', format: 'percent' },
          'Average Drawdown %': { key: 'avgDrawdownPct', format: 'percent' },
          'Maximum Drawdown': { key: 'maxDrawdown', format: 'currency' },
          'CAGR': { key: 'cagr', format: 'percent' },
          'Mean Return': { key: 'annualizedReturnPct', format: 'percent' },
          'StdDev(Return)': { key: 'stdDevPct', format: 'percent' },
          'Downside StdDev': { key: 'downsideStdDevPct', format: 'percent' },
          'StdDev(PnL)': { key: 'stdPnL', format: 'currency' },
          'StdDev': { key: 'stdDevPct', format: 'percent' },
          'Expected Value': { key: 'expectedValue', format: 'currency' },
          'EV': { key: 'expectedValue', format: 'currency' },
          'PnL > 0': { key: 'numWin', format: 'number' },
          'PnL < 0': { key: 'numLoss', format: 'number' },
          'N': { key: 'numTrades', format: 'number' },
          'W': { key: 'winRate', format: 'number' },
          'p': { key: 'winRate', format: 'number' },
          'R': { key: 'payoffRatio', format: 'number' },
          'Z': { key: 'zScore', format: 'number' },
          'Beta': { key: 'betaToBenchmark', format: 'number' },
          'TrackingErr': { key: 'trackingError', format: 'number' },
          'Stability': { key: 'equityCurveStability', format: 'percent' },
          'Kelly Criterion': { key: 'kellyCriterion', format: 'percent' },
          'Kelly': { key: 'kellyCriterion', format: 'percent' },
          'Skew': { key: 'skewness', format: 'number' },
          'Kurt': { key: 'kurtosis', format: 'number' },
          'Outliers': { key: 'outlierImpactRatio', format: 'number' },
          'Rf': { key: 'riskFree', format: 'percent', source: 'riskFree' },
          'Rm': { key: 'bench', format: 'percent', source: 'bench' },
          'Benchmark': { key: 'bench', format: 'percent', source: 'bench' },
          'Trades': { key: 'numTrades', format: 'number' },
          'Wins': { key: 'numWin', format: 'number' },
          'MeanPnL': { key: 'avgTrade', format: 'currency' },
          'P50(Trade PnLs)': { key: 'medianTradeResult', format: 'currency' },
          'Mean(PnLs < P05)': { key: 'cvar', format: 'currency' },
          'CVaR': { key: 'cvar', format: 'currency' },
          'Deposit': { key: 'initialDeposit', format: 'currency' },
          'Mean MAE': { key: 'mae', format: 'currency' },
          'Mean MFE': { key: 'mfe', format: 'currency' },
          'Z-Score': { key: 'zScore', format: 'number' },
          'Simulated Max Drawdowns': { key: 'monteCarloDrawdown', format: 'percent' },
          'Simulations Ruined': { key: 'monteCarloRiskOfRuin', format: 'percent' },
          'Simulated Net Returns': { key: 'monteCarloExpectedReturn', format: 'percent' },
          'Rolling 10-Trade Sharpe': { key: 'rollingSharpe', format: 'number' },
          'Rolling 10-Trade PF': { key: 'rollingProfitFactor', format: 'number' },
          'Rolling 10-Trade EV': { key: 'rollingExpectancy', format: 'currency' },
          'Rolling 10-Trade DD': { key: 'rollingDrawdown', format: 'percent' },
          'Rolling 10-Trade Win%': { key: 'rollingWinRate', format: 'percent' },
          'Decay Rate': { key: 'strategyDecayRate', format: 'number' }
        };"""

pattern = r"const terms: Record<string, \{ key: string, format: string, source\?: string \}> = \{.*?\n        \};"
new_content = re.sub(pattern, new_terms, content, flags=re.DOTALL)

with open('/Users/evanvosh/Documents/app1.1/src/shared/ui/components/ExEquityCurve3D.vue', 'w') as f:
    f.write(new_content)
print(f"Replaced {content.count('const terms: Record<string, { key: string, format: string, source?: string }> = {')} occurrences.")
